In [17]:
from sts.data.database import SymbolTable
from sts.data.yahoo.yhdata import YHData
import datetime

In [14]:
symbol_table = SymbolTable()

In [15]:
symbol_table = symbol_table.add_symbol(YahooSym="BTC-USD", Symbol="BTCUSD")
symbol_table = symbol_table.add_symbol(YahooSym="IWM", Symbol="IWM")
symbol_table

  YahooSym AssetClass  Symbol Description  SymId
0  BTC-USD       None  BTCUSD        None      0
0      IWM       None     IWM        None      1

In [18]:
sd = datetime.date(2020, 1, 1)
ed = datetime.date(2023, 9, 1)

In [19]:
yh_data = YHData(symbol_table=symbol_table)

In [20]:
df = yh_data.get_hist_data_for_symbols(["BTCUSD", "IWM"], sd, ed)

In [23]:
df = df.dropna()

In [26]:
df.apply(lambda x: x / x.iloc[0], axis=0)

              BTCUSD       IWM
Date
2020-01-02  1.000000  1.000000
2020-01-03  1.051452  0.996079
2020-01-06  1.112197  0.997406
2020-01-07  1.168668  0.994088
2020-01-08  1.156667  0.997165
...              ...       ...
2023-08-25  3.728835  1.160295
2023-08-28  3.737207  1.170636
2023-08-29  3.969295  1.186969
2023-08-30  3.907721  1.191446
2023-08-31  3.712201  1.189365

[923 rows x 2 columns]

In [27]:
import pandas as pd

In [29]:
pd.MultiIndex.from_arrays()

AttributeError: module 'pandas' has no attribute 'multindex'