In [22]:
#import packages
from stlib.utils.nbutils import set_notebook_content_width
import pandas as pd
import numpy as np
from zipfile import ZipFile

In [23]:
set_notebook_content_width(90)

### Context

this notebook is to replicate the work done in the post by [Daniel Shapiro](https://towardsdatascience.com/data-science-in-algorithmic-trading-d21a46d1565d)

### Data

#### CAD_USD Rate Data

daily exchange rates can be found [here](https://open.canada.ca/data/en/dataset/1bc25b1e-0e02-4a5e-afd7-7b96d6728aac)

In [6]:
historical_data = '../../data/fx_cad_usd_10100008-eng.zip'
zip_file = ZipFile(historical_data)

In [18]:
data = {}
for file in zip_file.filelist:
    if file.filename.endswith('csv'):
        data[file.filename] = pd.read_csv(zip_file.open(file.filename))

/home/yuqing42/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [21]:
data['10100008_MetaData.csv']

,Cube Title,Product Id,CANSIM Id,URL,Cube Notes,Archive Status,Frequency,Start Reference Period,End Reference Period,Total number of dimensions,Universe,Variable List
0,"Foreign exchange rates in Canadian dollars, Ba...",10100008,176-0067,https://www150.statcan.gc.ca/t1/tbl1/en/tv.act...,1;2;3,ARCHIVED - a cube publicly available but no l...,Daily,1950-10-02,2017-04-28,2,NaN,NaN
1,Dimension ID,Dimension name,Dimension Notes,Dimension Correction Notes,Dimension Definitions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Geography,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,Type of currency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dimension ID,Member Name,Classification Code,Member ID,Parent Member ID,Terminated,Member Notes,Member Correction Notes,Member Geo Attribute Keys,Member Definitions,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
70,Note ID,Note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,1,"A numeric value ""0"" indicates a weekend.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,2,"Effective March 2, 2017, the Bank of Canada ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,3,"Effective March 2, 2017, the Canadian-Dollar E...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Dimension ID,Member ID,Attribute Key,Title,Label,Long Label,Value,NaN,NaN,NaN,NaN,NaN

In [24]:
data['10100008.csv']

,REF_DATE,GEO,DGUID,Type of currency,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1950-10-02,Canada,NaN,"United States dollar, noon spot rate",Dollars,81,units,0,v121716,1.10,1.060000,NaN,NaN,NaN,8
1,1950-10-02,Canada,NaN,"Danish krone, noon spot rate",Dollars,81,units,0,v121743,1.40,0.153459,NaN,NaN,NaN,8
2,1950-10-02,Canada,NaN,"Norwegian krone, noon spot rate",Dollars,81,units,0,v121717,1.10,0.148400,NaN,NaN,NaN,8
3,1950-10-02,Canada,NaN,"Swedish krona, noon spot rate",Dollars,81,units,0,v121718,1.11,0.204800,NaN,NaN,NaN,8
4,1950-10-02,Canada,NaN,"Swiss franc, noon spot rate",Dollars,81,units,0,v121719,1.12,0.243400,NaN,NaN,NaN,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534277,2017-04-28,Canada,NaN,"New Zealand dollar, closing spot rate",Dollars,81,units,0,v21603850,1.40,0.937300,NaN,NaN,NaN,8
534278,2017-04-28,Canada,NaN,"Norwegian krone, closing spot rate",Dollars,81,units,0,v21603851,1.41,0.159000,NaN,NaN,NaN,8
534279,2017-04-28,Canada,NaN,"Swedish krona, closing spot rate",Dollars,81,units,0,v21603852,1.42,0.154100,NaN,NaN,NaN,8
534280,2017-04-28,Canada,NaN,"Swiss franc, closing spot rate",Dollars,81,units,0,v21603853,1.43,1.371900,NaN,NaN,NaN,8
534281,2017-04-28,Canada,NaN,"United Kingdom pound sterling, closing spot rate",Dollars,81,units,0,v21603854,1.44,1.767900,NaN,NaN,NaN,8

In [1]:
20 * 100k

SyntaxError: invalid syntax (<ipython-input-1-c6ee9ba461b0>, line 1)