In [7]:
import pandas as pd
from datetime import datetime, date

In [57]:
td = date(2026, 1, 12)
all_df = None
for interval in ['1d', '1W', '1ME']:
    stock_df = pd.read_parquet(f'/home/yuqing42/data/stsdata/research/us_stock/{interval}/{td.strftime('%Y%m%d')}')
    stock_df = stock_df.set_index('symbol')
    if all_df is None:
        all_df = stock_df
    else:
        all_df = pd.merge(all_df, stock_df, left_index = True, right_index = True, how = 'outer')
# etf_df = pd.read_parquet('/home/yuqing42/data/stsdata/research/us_etf/1d/20260112')

In [14]:
all_df.loc['ORCL']

ts_1d    -0.138618
ts_1W    -0.432270
ts_1ME    0.232782
Name: ORCL, dtype: float64

In [ ]:
# long term up, intermediate down, short term up
idx = (all_df['ts_1d'] > -0.2) & (all_df['ts_1W'] < -0.4) & (all_df['ts_1ME'] > 0.2)
all_df[idx]

           ts_1d    ts_1W    ts_1ME
symbol
ORCL   -0.138618 -0.43227  0.232782
SE      0.251192 -0.40562  0.251797

In [59]:
all_df.sort_values('ts_1W', ascending=False).head(100)

           ts_1d     ts_1W    ts_1ME
symbol
RVMD    1.470910  1.467409  1.068667
TEVA    0.724297  1.428149  1.067837
LITE    0.095936  1.403447  1.746028
AXTI    0.958085  1.388701  1.431002
SATS    0.847719  1.369991  1.482868
AA      1.333558  1.343981  0.565529
WBD     0.292780  1.339017  1.219484
MU      1.057690  1.289581  1.260409
CIEN    0.189720  1.181324  1.540717
GM      0.452061  1.179552  1.002285
AEO     0.423301  1.168819  0.543244
PL      0.863588  1.158347  1.382977
RIO     0.734368  1.154448  0.545637
SNDK    1.057187  1.133349       NaN
HL      0.558921  1.094357  1.328973
LRCX    1.158257  1.088508 -0.469150
ALB     0.804639  1.083063  0.395885
TER     0.713496  1.065393  0.825242
B       0.642291  1.046996  0.274431
WDC     0.436942  1.034020  1.315083
GOOG    0.445564  1.027766  1.143842
CMI     0.777120  1.026761  1.047524
GOOGL   0.455140  1.024719  1.141421
EXPD    0.663593  1.010387  0.594125
CHRW    0.504811  0.977915  1.065618
PAAS    0.413857  0.974285  1.080229
BBIO    0.120870  0.972891  1.023756
DG      0.783110  0.971418  0.321897
ROST    0.757850  0.960776  0.619060
VALE    0.833983  0.956875  0.386352
C       0.696423  0.925693  1.071021
COHR   -0.006866  0.925180  0.926326
FIVE    0.655485  0.911885  0.551189
NEM     0.587428  0.907935  1.141529
CAH    -0.011981  0.893216  1.093501
GH      0.413280  0.890253  1.060452
EXPE    0.595482  0.889939  0.914190
ANF     0.599245  0.889251  0.099067
EA      0.167798  0.888296  0.916560
AMAT    0.807824  0.882694  0.630201
GS      0.678971  0.861204  1.056281
LLY     0.185028  0.858920  0.528603
NTRA    0.266542  0.843347  0.908543
FDX     0.855678  0.829080  0.282107
MDB     0.065964  0.827651  0.435101
SCCO    0.934496  0.825028  0.678234
ASML    1.048325  0.824396  0.606341
REGN    0.487971  0.819250  0.056417
AG      0.483492  0.814588  0.998913
ILMN    0.617997  0.813941  0.218452
ULTA    1.008299  0.809632  0.628631
MRK     0.723790  0.792184  0.085647
CFG     0.571959  0.791495  0.668581
PH      0.498387  0.780612  0.848968
CAT     0.415183  0.778854  0.972719
MS      0.583974  0.773792  0.912554
LUV     0.757976  0.765630  0.394320
JNJ    -0.063491  0.760607  0.779841
MDGL   -0.338249  0.751185  0.785529
DLTR    0.582176  0.749591  0.369250
KLAC    0.684340  0.740265  0.907862
SYF     0.553947  0.734853  0.796596
AZN     0.451765  0.729110  0.558137
BK      0.467946  0.728017  1.160811
TPR     0.663949  0.724286  1.046184
STX     0.237013  0.721215  1.339965
FTAI    1.482143  0.712708  0.642157
STT     0.480064  0.707448  0.765277
MNST    0.230294  0.707239  0.635679
KEY     0.549103  0.698262  0.414576
BIIB    0.536417  0.698199  0.047690
USB     0.541821  0.697234  0.374595
RTX     0.421042  0.694397  1.022003
FCX     0.940955  0.691074  0.272080
ONDS    0.926043  0.690263  1.053494
BHP     0.563821  0.676898  0.252838
ADI     0.881709  0.670274  0.503723
RKLB    0.814578  0.670175  1.000869
TJX     0.268278  0.661376  0.843100
BMY     0.597942  0.653885  0.050886
MAR     0.675221  0.650541  0.482985
COMP    0.776381  0.646703  0.583508
LUNR    0.883256  0.642751  0.275435
RIVN    0.092229  0.635762  0.304841
CRL     0.892104  0.631273  0.137264
BIDU    0.784648  0.628179  0.387640
COF     0.572421  0.624863  0.661584
DAL     0.395037  0.623302  0.464928
TMO     0.663279  0.620542  0.271104
WPM     0.452531  0.612721  1.000860
ROK     0.311685  0.609748  0.664321
WFC     0.434810  0.607100  0.679855
CTSH    0.344916  0.604873  0.205986
CRS     0.109553  0.600499  0.994923
FIX     0.226829  0.598991  1.222515
TFC     0.409326  0.591017  0.351464
PNC     0.652226  0.589909  0.354711
IQV     0.758302  0.589773  0.266671
AAL     0.331485  0.588812  0.208707
GLW    -0.136909  0.584140  1.161638

In [47]:
td = date(2026, 1, 12)
all_df = None
asset = 'us_etf'
for interval in ['1d', '1W', '1ME']:
    stock_df = pd.read_parquet(f'/home/yuqing42/data/stsdata/research/{asset}/{interval}/{td.strftime('%Y%m%d')}')
    stock_df = stock_df.set_index('symbol')
    if all_df is None:
        all_df = stock_df
    else:
        all_df = pd.merge(all_df, stock_df, left_index = True, right_index = True, how = 'outer')
# etf_df = pd.read_parquet('/home/yuqing42/data/stsdata/research/us_etf/1d/20260112')

In [48]:
# long term up, intermediate down, short term up
idx = (all_df['ts_1d'] > -0.2) & (all_df['ts_1W'] < -0.4) & (all_df['ts_1ME'] > 0.2)
all_df[idx]

           ts_1d     ts_1W    ts_1ME
symbol
STIP   -0.106767 -0.405249  0.321343

In [53]:
pd.options.display.max_rows = 100
all_df.sort_values('ts_1W', ascending=False).dropna().head(100)

           ts_1d     ts_1W    ts_1ME
symbol
BOXX    1.920975  2.824163  2.560496
SDS     0.202904  2.434335  1.421929
SIVR    0.865305  1.668679  1.602750
SLV     0.861267  1.657899  1.599650
SPXU    0.026200  1.627700  0.833178
PSLV    0.866948  1.626155  1.538354
AGQ     0.695678  1.468643  1.569787
SQQQ    0.052310  1.443806  0.880671
CEF     0.699007  1.349574  1.630521
PLTM    0.695901  1.146851  1.311078
DXJ     1.078891  1.139728  1.111162
PPLT    0.692629  1.136483  1.298093
COPX    0.744714  1.110785  1.008811
PICK    0.998095  1.076202  0.674513
ALBpA   0.893789  1.062219  0.548179
EWY     1.419000  1.053686  1.005986
SLVP    0.529069  1.031097  1.422491
SPXS   -0.304864  1.015474  1.471887
VLUE    0.923033  1.011548  0.939558
SRTY   -0.274321  1.006476  0.302380
MSTY    0.425372  0.999707  0.031300
IAUM    0.545293  0.972012  1.594555
GLDM    0.542748  0.970513  1.590109
SGOL    0.545342  0.969850  1.588939
OUNZ    0.546100  0.968789  1.586802
AAAU    0.545051  0.968587  1.597758
IAU     0.541179  0.966703  1.584131
DFIV    0.701464  0.956178  1.034928
GLD     0.534617  0.953894  1.578302
EWP     0.614882  0.950132  1.284130
PVAL    0.731109  0.920165  0.929779
PHYS    0.492167  0.917772  1.526873
XBI     0.184278  0.912291  0.703666
SIL     0.429387  0.912208  1.302000
GGLL    0.382077  0.910305  1.035070
SILJ    0.451372  0.910096  1.220895
AVDV    0.943455  0.898385  1.142699
XME     0.898751  0.880043  1.107425
GDXJ    0.425724  0.874855  1.313573
GDX     0.483062  0.870017  1.332273
PALL    0.478555  0.857826  0.763327
JNUG    0.439744  0.851351  1.286979
IVLU    0.742770  0.850426  0.970513
EWC     0.381779  0.849640  1.083374
LABU    0.128613  0.829232  0.573006
VYMI    0.663829  0.828275  0.916658
NUGT    0.472286  0.818667  1.287208
TSLZ    0.191788  0.816423  0.051043
DFIC    0.937396  0.809692  0.921423
IBB     0.236667  0.806267  0.671389
EMXC    1.213391  0.794079  0.857150
KBWB    0.626259  0.771053  0.777608
DFAI    0.878435  0.761451  0.870921
AVDE    0.871344  0.755272  0.921813
GDXU    0.430048  0.736507  1.138459
FNDF    0.800187  0.723367  0.910608
REMX    0.915457  0.714411  0.720312
SVXY    0.720043  0.698497 -0.063268
SMH     0.646220  0.690536  0.819096
ITA     0.909275  0.677307  1.097576
XAR     1.116164  0.672270  1.078719
VHT     0.405348  0.669931  0.405544
RDVY    0.769544  0.667216  0.698779
EFV     0.498619  0.664560  0.867472
VEA     0.856546  0.664176  0.810673
SPDW    0.817825  0.662759  0.839864
PPA     1.025129  0.660508  1.106265
EZA     0.421002  0.656751  0.901532
VGK     0.908434  0.652394  0.712113
FNDX    0.681005  0.650171 -0.753185
JETS    0.553909  0.648006  0.539266
XLV     0.408247  0.647255  0.347461
FENI    0.770466  0.645529  0.749827
SOXX    0.624200  0.644872  0.198051
EWU     0.626072  0.642390  0.753009
SOXQ    0.531250  0.637830  0.769434
ILF     0.500607  0.636947  0.544094
VONV    0.695484  0.634052  0.649503
DFAE    1.043589  0.631337  0.816875
IWD     0.699045  0.625100  0.636614
VEU     0.836347  0.620417  0.806464
SVIX    0.687319  0.620333 -0.090807
ACWX    0.846837  0.619468  0.793325
GLL    -0.248022  0.611010  0.287901
EEM     1.007818  0.607883  0.801986
UVXY   -0.369068  0.607095  0.288633
CGDV    0.398763  0.605003  1.010520
IEUR    0.850842  0.599098  0.689244
VXUS    0.803833  0.597174  0.798919
VTV     0.604852  0.594715  0.649536
EZU     0.829785  0.586559  0.747307
VFLO    0.503183  0.581731  0.645235
FEZ     0.719007  0.579788  0.714285
AVEM    0.866152  0.578890  0.821052
DIA     0.543727  0.578364  0.691628
IXUS    0.826626  0.574542  0.781665
SCHF    0.825985  0.573892 -0.278598
COWZ    0.437197  0.573456  0.373904
AIRR    0.662904  0.569212  0.834132
IDEV    0.730675  0.568296  0.750881

In [ ]:
from sts.data.ticker import Ticker
from sts.quant.candle import Candle

In [26]:
etf_ticker = Ticker('us/etf.yml')

In [43]:
res = etf_ticker.top_trading_symbols('20260109', top_n=10000)

In [54]:
df = Candle(etf_ticker.history('SQQQ', '20250101', '20260109', '1d').set_index('ts'))

In [56]:
df.plot()