In [1]:
from sts.data.cftc import CFTCData, cot_reports

In [2]:
from IPython.display import display, HTML

display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
# Example: cot_hist()
df = cot_reports.cot_year(year=2023, cot_report_type="traders_in_financial_futures_fut")

Selected: traders_in_financial_futures_fut
Downloaded single year data from: 2023

In [17]:
df["Market_and_Exchange_Names"].unique()

array(['CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE',
       'SWISS FRANC - CHICAGO MERCANTILE EXCHANGE',
       'BRITISH POUND - CHICAGO MERCANTILE EXCHANGE',
       'JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE',
       'EURO FX - CHICAGO MERCANTILE EXCHANGE',
       'AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE',
       'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
       'EURO FX/JAPANESE YEN XRATE - CHICAGO MERCANTILE EXCHANGE',
       'MEXICAN PESO - CHICAGO MERCANTILE EXCHANGE',
       'BRAZILIAN REAL - CHICAGO MERCANTILE EXCHANGE',
       'NZ DOLLAR - CHICAGO MERCANTILE EXCHANGE',
       'SO AFRICAN RAND - CHICAGO MERCANTILE EXCHANGE',
       'DJIA Consolidated - CHICAGO BOARD OF TRADE',
       'DJIA x $5 - CHICAGO BOARD OF TRADE',
       'DOW JONES U.S. REAL ESTATE IDX - CHICAGO BOARD OF TRADE',
       'MICRO E-MINI DJIA (x$0.5) - CHICAGO BOARD OF TRADE',
       'S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P CONSU STAPLES INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P ENERGY INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P FINANCIAL INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P HEALTH CARE INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P INDUSTRIAL INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P MATERIALS INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P TECHNOLOGY INDEX - CHICAGO MERCANTILE EXCHANGE',
       'E-MINI S&P UTILITIES INDEX - CHICAGO MERCANTILE EXCHANGE',
       'MICRO E-MINI S&P 500 INDEX - CHICAGO MERCANTILE EXCHANGE',
       'ADJUSTED INT RATE S&P 500 TOTL - CHICAGO MERCANTILE EXCHANGE',
       'NASDAQ-100 Consolidated - CHICAGO MERCANTILE EXCHANGE',
       'NASDAQ MINI - CHICAGO MERCANTILE EXCHANGE',
       'MICRO E-MINI NASDAQ-100 INDEX - CHICAGO MERCANTILE EXCHANGE',
       'RUSSELL E-MINI - CHICAGO MERCANTILE EXCHANGE',
       'EMINI RUSSELL 1000 VALUE INDEX - CHICAGO MERCANTILE EXCHANGE',
       'MICRO E-MINI RUSSELL 2000 INDX - CHICAGO MERCANTILE EXCHANGE',
       'NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCHANGE',
       'NIKKEI STOCK AVERAGE YEN DENOM - CHICAGO MERCANTILE EXCHANGE',
       'MSCI EAFE  - ICE FUTURES U.S.',
       'MSCI EM INDEX - ICE FUTURES U.S.',
       'E-MINI S&P 400 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE',
       'S&P 500 ANNUAL DIVIDEND INDEX - CHICAGO MERCANTILE EXCHANGE',
       'S&P 500 QUARTERLY DIVIDEND IND - CHICAGO MERCANTILE EXCHANGE',
       'UST BOND - CHICAGO BOARD OF TRADE',
       'ULTRA UST BOND - CHICAGO BOARD OF TRADE',
       'UST 2Y NOTE - CHICAGO BOARD OF TRADE',
       'UST 10Y NOTE - CHICAGO BOARD OF TRADE',
       'ULTRA UST 10Y - CHICAGO BOARD OF TRADE',
       'MICRO 10 YEAR YIELD - CHICAGO BOARD OF TRADE',
       'UST 5Y NOTE - CHICAGO BOARD OF TRADE',
       'FED FUNDS - CHICAGO BOARD OF TRADE',
       'EURO SHORT TERM RATE - CHICAGO MERCANTILE EXCHANGE',
       'EURODOLLARS-3M - CHICAGO MERCANTILE EXCHANGE',
       'SOFR-3M - CHICAGO MERCANTILE EXCHANGE',
       'SOFR-1M - CHICAGO MERCANTILE EXCHANGE',
       '2 YEAR ERIS SOFR SWAP - CHICAGO BOARD OF TRADE',
       '10 YEAR ERIS SOFR SWAP - CHICAGO BOARD OF TRADE',
       '5 YEAR ERIS SOFR SWAP - CHICAGO BOARD OF TRADE',
       'BITCOIN - CHICAGO MERCANTILE EXCHANGE',
       'MICRO BITCOIN - CHICAGO MERCANTILE EXCHANGE',
       'ETHER CASH SETTLED - CHICAGO MERCANTILE EXCHANGE',
       'MICRO ETHER  - CHICAGO MERCANTILE EXCHANGE',
       'USD INDEX - ICE FUTURES U.S.',
       'VIX FUTURES - CBOE FUTURES EXCHANGE',
       'BBG COMMODITY - CHICAGO BOARD OF TRADE'], dtype=object)

In [21]:
# instr = '10-YEAR U.S. TREASURY NOTES - CHICAGO BOARD OF TRADE'
instr2 = "NASDAQ-100 Consolidated - CHICAGO MERCANTILE EXCHANGE"
df2 = df[df["Market_and_Exchange_Names"] == instr2].copy()

In [22]:
df3 = CFTCData(df2)

In [23]:
df3.position.head(100).reset_index()

       rptDate Dealer               Asset_Mgr               Lev_Money
                 Long  Short Spread      Long  Short Spread      Long   Short
0   2023-08-15  51410  67762   4075     91705  28830   6157     38954   77535  \
1   2023-08-08  52803  62768   3543     93838  27319   6136     37985   97053
2   2023-08-01  47696  61185   3769     95911  30754   5240     40282   93951
3   2023-07-25  44688  72557   3355     94940  30870   6146     39912   79516
4   2023-07-18  37533  75492   3263     96423  24979   7638     46820   76385
5   2023-07-11  39746  67877   2618     92160  28126   7026     43740   80417
6   2023-07-03  36736  65149   2766     91364  28692   7360     44081   76610
7   2023-06-27  40739  72336   2833     90580  25455   7564     50148   75344
8   2023-06-20  37045  73875   1385     93134  25816   6507     53986   69993
9   2023-06-13  47592  58001  26326     92653  21853  10762     61041  101170
10  2023-06-06  42327  67824   9992     95470  23056   7359     73478  111628
11  2023-05-30  43679  60478   8348     93537  28824   7986     70386  110343
12  2023-05-23  42636  55579   6796     91039  32184   8756     64908   98840
13  2023-05-16  40625  51425   4922     89061  37925   9637     64723   92432
14  2023-05-09  34203  44576   4603     82954  38373   9486     56149   85997
15  2023-05-02  35815  40996   3850     82084  38832   9341     49705   84041
16  2023-04-25   8084   8381    585     15845   7615   1968     10320   17518
17  2023-04-18   8295   7517    571     16242   8519   1596     10914   17239
18  2023-04-11   8120   7507    565     15919   7868   1721      9744   16986
19  2023-04-04   8456   5668    468     13827   7293   1591      9229   18097
20  2023-03-28   9385   3680    241     14944  10080   1623      8215   16394
21  2023-03-21   8688   3693    175     14981  10112   1759      8682   14768
22  2023-03-14  12338   6203   4001     14787  10776   2707     13031   14237
23  2023-03-07  14032   6392    353     14293   9442   1613     11958   17529
24  2023-02-28  15349   7381    282     14796   9959   1705     11732   17971
25  2023-02-21  15171   8014    190     15121   8426   2050     11660   18627
26  2023-02-14  15729   8547    206     16666   7471   1558     11796   20966
27  2023-02-07  14376  10392    293     17658   7878   1573     13475   21268
28  2023-01-31  14603   9722    260     17864  10258   1550     12323   17989
29  2023-01-24  13629   8752    228     17631  10414   1951     11607   17469
30  2023-01-17  13417   9099    272     17126  11496   1899     12546   16141
31  2023-01-10  11480   9262    342     16007  12516   1719     11626   14082
32  2023-01-03   9946   8282    744     14812  13663   1794     11721   12084

          Other_Rept               Tot_Rept         NonRept
   Spread       Long  Short Spread     Long   Short    Long  Short
0   25943      12495  23556   3316   234056  237176   47237  44118
1   27136      14038  11525    563   236042  236043   45605  45604
2   26104      13164  11176    644   232810  232823   43722  43709
3   24900      12153  11820    630   226724  229794   46186  43116
4   27474      16428  12707    358   235938  228297   42530  50171
5   23331      18691  15071    221   227532  224687   44259  47104
6   18370      14483  14062    216   215375  213224   43768  45919
7   12932      16297  18486    264   221356  215213   44461  50604
8    7235      13086  19047    139   212517  203998   42521  51041
9   27111      24490  27773   2459   292432  275454   42904  59883
10  24179      22346  16062    771   275923  260872   42161  57213
11  20785      24064  15007    846   269631  252618   40437  57450
12  15527      12770  13871    728   243159  232281   42424  53302
13  15323      18651  15391    518   243460  227573   40325  56212
14  13087      23210  16714    445   224138  213281   40461  51318
15   9735      27008  17761    357   217893  204912   38061  51042
16   1401       4289   3304      2    42493   40773    7038   8757
17   1388       2979   3337      1    41986   40168    7026   8844
18   1326       2655   2919     71    40120   38962    7374   8532
19   1332       1299   2919      1    36202   37368   10235   9069
20    651       2227   3118      6    37292   35792    6723   8222
21    673       1678   3108      1    36636   34288    6339   8687
22   3470       2002   5227    120    52457   46741    8835  14551
23   1386       1918   4107     14    45567   40837    6595  11325
24   1252       1720   4650     16    46851   43216    6800  10435
25    992       1463   4237     32    46680   42570    6979  11089
26    820       1473   4579      7    48256   44153    6981  11083
27    738       1455   4379     14    49582   46535    6280   9326
28   1210       1689   5271      4    49503   46264    6187   9426
29   1279       1880   5748      4    48208   45845    6569   8933
30   1258       1930   6301      3    48451   46469    6552   8534
31   1075       1643   3741    241    44133   42977    6592   7748
32    946       2069   3412      2    42035   40927    6897   8005

In [24]:
df3.change.reset_index()

       rptDate        OI    Dealer                     Asset_Mgr
                              Long     Short    Spread      Long     Short
0   2023-08-15      -353     -1393      4995       532     -2133      1511  \
1   2023-08-08      5115      5107      1583      -226     -2073     -3435
2   2023-08-01      3621      3008    -11372       414       971      -116
3   2023-07-25     -5558      7155     -2936        92     -1483      5891
4   2023-07-18      6677     -2213      7616       645      4263     -3147
5   2023-07-11     12648      3010      2728      -148       796      -566
6   2023-07-03     -6675     -4003     -7187       -67       784      3237
7   2023-06-27     10779      3694     -1539      1448     -2554      -361
8   2023-06-20    -80298    -10548     15874    -24941       482      3963
9   2023-06-13     17252      5265     -9823     16333     -2818     -1203
10  2023-06-06      8017     -1351      7346      1644      1933     -5768
11  2023-05-30     24485      1042      4899      1552      2498     -3360
12  2023-05-23      1798      2012      4154      1874      1978     -5741
13  2023-05-16     19186      6421      6849       319      6107      -448
14  2023-05-09      8645     -1612      3580       754       871      -459
15  2023-05-02    206423     27731     32615      3265     66239     31217
16  2023-04-25       519      -211       864        14      -397      -904
17  2023-04-18      1518       175        11         6       323       652
18  2023-04-11      1057      -335      1839        96      2091       575
19  2023-04-04      2422      -929      1988       227     -1117     -2787
20  2023-03-28      1040       697       -13        66       -37       -32
21  2023-03-21    -18317     -3651     -2510     -3826       194      -664
22  2023-03-14      9130     -1694      -190      3649       494      1334
23  2023-03-07     -1489     -1317      -989        71      -503      -517
24  2023-02-28        -9       177      -633        92      -325      1533
25  2023-02-21     -1577      -558      -533       -16     -1545       955
26  2023-02-14      -624      1354     -1845       -87      -992      -407
27  2023-02-07       171      -227       670        33      -206     -2380
28  2023-01-31       912       975       970        32       233      -156
29  2023-01-24      -226       211      -347       -44       505     -1082
30  2023-01-17      4278      1937      -163       -70      1119     -1020
31  2023-01-10      1793      1535       980      -403      1195     -1147
32  2023-01-03     -1225     -1478       307       576      -730        -2

             Lev_Money                     Other_Rept
      Spread      Long     Short    Spread       Long     Short    Spread
0         21       969    -19518     -1192      -1543     12031      2753  \
1        896     -2297      3102      1031        874       349       -81
2       -905       370     14435      1204       1012      -644        14
3      -1493     -6908      3131     -2573      -4275      -887       272
4        612      3081     -4032      4143      -2263     -2364       138
5       -334      -342      3807      4961       4208      1010         5
6       -204     -6067      1266      5438      -1814     -4424       -48
7       1056     -3838      5351      5697       3211      -561       125
8      -4254     -7054    -31177    -19875     -11405     -8727     -2320
9       3403    -12438    -10458      2932       2144     11711      1688
10      -627      3092      1285      3394      -1718      1055       -75
11      -770      5479     11503      5258      11294      1136       118
12      -881       185      6408       204      -5882     -1520       210
13       151      8575      6435      2236      -4559     -1323        73
14       145      6444      1956      3353      -3798     -1047        88
15      7373     39385     66523      8334      22718     14457       355
16       372      -594       279        13       1310       -33         1
17      -125      1170       252        62        324       418       -70
18       130       515     -1111        -6       1356         0        70
19       -32      1014      1703       680       -928      -199        -6
20      -136      -467      1626       -21        549        10         6
21      -948     -4349       531     -2797       -324     -2119      -120
22      1094      1074     -3292      2084         84      1120       107
23       -92       226      -442       135        198      -543        -2
24      -345        71      -657       260        257       412       -16
25       492      -136     -2338       172        -10      -342        25
26       -15     -1679      -303        82         18       201        -7
27        23      1152      3280      -472       -234      -893        11
28      -401       716       520       -68       -191      -476        -1
29        52      -939      1327        21        -50      -553         1
30       180       920      2060       183        287      2560      -238
31       -76       -95      1998       129       -427       330       239
32       -84       622     -2076       -30        158        53      -251

    Tot_Rept             NonRept
        Long     Short      Long     Short
0      -1985      1133      1632     -1486
1       3231      3220      1884      1895
2       6086      3029     -2465       593
3      -9214      1497      3656     -7055
4       8407      3610     -1729      3067
5      12156     11463       491      1185
6      -5981     -1989      -693     -4685
7       8839     11216      1940      -437
8     -79915    -71456      -383     -8842
9      16509     14582       743      2670
10      6293      8254      1724      -237
11     26472     20337     -1987      4148
12      -301      4708      2099     -2910
13     19322     14292      -137      4894
14      6245      8369      2401       277
15    175400    164139     31023     42284
16       507       605        12       -86
17      1866      1206      -348       312
18      3918      1594     -2861      -538
19     -1090      1576      3512       847
20       656      1504       383      -465
21    -15821    -12453     -2496     -5864
22      6891      5905      2240      3226
23     -1284     -2379      -204       891
24       171       646      -179      -655
25     -1576     -1583        -2         6
26     -1326     -2382       701      1757
27        79       271        93      -100
28      1295       419      -382       493
29      -243      -624        17       399
30      4318      3492       -40       786
31      2098      2050      -304      -257
32     -1216     -1507        -9       282