In [1]:
from sts.data import yh_data
from sts.strategy.pca.pca_analysis import PCATS
import datetime
import pandas as pd
import numpy as np

In [57]:
fx_table = yh_data.symbol_table.query('AssetClass == "FX"').iloc[np.asarray([0, 1, 6, 7, 8, 9])]
fx_table

    SymId AssetClass  Symbol       Description  YahooSym
30     31         FX  EURUSD              EURO  EURUSD=X
31     32         FX  GBPUSD    Pound Sterling  GBPUSD=X
36     37         FX  CHFUSD       Swiss Franc  CHFUSD=X
37     38         FX  NOKUSD   Norwegian Krone  NOKUSD=X
38     39         FX  SEKUSD     Swedish Krona  SEKUSD=X
39     40         FX  SGDUSD  Singapore Dollar  SGDUSD=X

## High correlation fitler

In [49]:
fx_table = yh_data.symbol_table.query('AssetClass == "FX"')

# configuration
look_back_history = 360
cov_matrix_diff = 5
ed = datetime.date.today()  # datetime.date.today()
sd = ed - datetime.timedelta(days=look_back_history)

corr_threshold = 0.7

In [50]:
data_df = yh_data.get_hist_data_for_symbols(fx_table["Symbol"].to_list(), sd, ed, column="Close")
pcatts = PCATS(data_df, cov_mat_diff_days=cov_matrix_diff)
pcatts.corr_mat

,EURUSD,GBPUSD,USDJPY,AUDUSD,NZDUSD,CADUSD,CHFUSD,NOKUSD,SEKUSD,SGDUSD,PENUSD,BRLUSD
EURUSD,1.000000,0.825204,-0.564968,-0.690254,0.701448,0.557185,0.832993,0.652448,0.827628,0.832663,0.160086,0.041596
GBPUSD,0.825204,1.000000,-0.425280,-0.610155,0.674159,0.457351,0.641361,0.582493,0.780875,0.726174,0.006256,-0.142298
USDJPY,-0.564968,-0.425280,1.000000,0.625533,-0.578605,-0.366712,-0.584067,-0.525131,-0.489639,-0.746173,-0.228554,-0.105861
AUDUSD,-0.690254,-0.610155,0.625533,1.000000,-0.853889,-0.763754,-0.665613,-0.693554,-0.665212,-0.817156,-0.116239,-0.260698
NZDUSD,0.701448,0.674159,-0.578605,-0.853889,1.000000,0.676980,0.626173,0.666801,0.676435,0.800329,0.177530,0.167283
CADUSD,0.557185,0.457351,-0.366712,-0.763754,0.676980,1.000000,0.529732,0.649060,0.532315,0.596066,0.137111,0.404234
CHFUSD,0.832993,0.641361,-0.584067,-0.665613,0.626173,0.529732,1.000000,0.639990,0.728392,0.722853,0.232624,-0.000968
NOKUSD,0.652448,0.582493,-0.525131,-0.693554,0.666801,0.649060,0.639990,1.000000,0.756294,0.724560,0.189136,0.284706
SEKUSD,0.827628,0.780875,-0.489639,-0.665212,0.676435,0.532315,0.728392,0.756294,1.000000,0.736892,0.102764,0.001360
SGDUSD,0.832663,0.726174,-0.746173,-0.817156,0.800329,0.596066,0.722853,0.724560,0.736892,1.000000,0.216262,0.175939
PENUSD,0.160086,0.006256,-0.228554,-0.116239,0.177530,0.137111,0.232624,0.189136,0.102764,0.216262,1.000000,0.392358
BRLUSD,0.041596,-0.142298,-0.105861,-0.260698,0.167283,0.404234,-0.000968,0.284706,0.001360,0.175939,0.392358,1.000000

In [53]:
pcatts.corr_mat[(pcatts.corr_mat.abs() >= corr_threshold)]

,EURUSD,GBPUSD,USDJPY,AUDUSD,NZDUSD,CADUSD,CHFUSD,NOKUSD,SEKUSD,SGDUSD,PENUSD,BRLUSD
EURUSD,1.000000,0.825204,NaN,NaN,0.701448,NaN,0.832993,NaN,0.827628,0.832663,NaN,NaN
GBPUSD,0.825204,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.780875,0.726174,NaN,NaN
USDJPY,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,-0.746173,NaN,NaN
AUDUSD,NaN,NaN,NaN,1.000000,-0.853889,-0.763754,NaN,NaN,NaN,-0.817156,NaN,NaN
NZDUSD,0.701448,NaN,NaN,-0.853889,1.000000,NaN,NaN,NaN,NaN,0.800329,NaN,NaN
CADUSD,NaN,NaN,NaN,-0.763754,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
CHFUSD,0.832993,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,0.728392,0.722853,NaN,NaN
NOKUSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.756294,0.724560,NaN,NaN
SEKUSD,0.827628,0.780875,NaN,NaN,NaN,NaN,0.728392,0.756294,1.000000,0.736892,NaN,NaN
SGDUSD,0.832663,0.726174,-0.746173,-0.817156,0.800329,NaN,0.722853,0.724560,0.736892,1.000000,NaN,NaN
PENUSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
BRLUSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

## Get Cov Matrix and PCA

In [61]:
# configuration
look_back_history = 360
cov_matrix_diff = 5
ed = datetime.date.today()  # datetime.date.today()
sd = ed - datetime.timedelta(days=look_back_history)

In [62]:
data_df = yh_data.get_hist_data_for_symbols(fx_table["Symbol"].to_list(), sd, ed, column="Close")

In [63]:
pcatts = PCATS(data_df, cov_mat_diff_days=cov_matrix_diff)

In [64]:
pcatts.corr_mat

          EURUSD    GBPUSD    CHFUSD    NOKUSD    SEKUSD    SGDUSD
EURUSD  1.000000  0.825204  0.832993  0.652448  0.827628  0.832663
GBPUSD  0.825204  1.000000  0.641361  0.582493  0.780875  0.726174
CHFUSD  0.832993  0.641361  1.000000  0.639990  0.728392  0.722853
NOKUSD  0.652448  0.582493  0.639990  1.000000  0.756294  0.724560
SEKUSD  0.827628  0.780875  0.728392  0.756294  1.000000  0.736892
SGDUSD  0.832663  0.726174  0.722853  0.724560  0.736892  1.000000

In [65]:
pcatts.pca_mat

            PCA1      PCA2      PCA3      PCA4      PCA5      PCA6
EURUSD  0.323648  0.252971  0.251659  0.103422  0.497859  0.713699
GBPUSD  0.423788  0.542577 -0.459722  0.466352 -0.301375 -0.079740
CHFUSD  0.329058  0.111606  0.812703  0.067117 -0.421696 -0.190910
NOKUSD  0.520134 -0.786101 -0.143125  0.263232 -0.089236  0.117334
SEKUSD  0.540383  0.104064 -0.186008 -0.806856  0.010710 -0.106900
SGDUSD  0.211716  0.019400  0.098760  0.216813  0.689496 -0.650103

In [66]:
pca_vol_year = pcatts.pca_vol.to_frame()
pca_vol_year * 100

            vol
PCA1  23.077287
PCA2   8.510304
PCA3   5.981589
PCA4   5.263163
PCA5   3.266753
PCA6   2.328505

In [79]:
# longer term test
look_back_history = 360 * 5
ed = datetime.date.today()  # datetime.date.today()
sd = ed - datetime.timedelta(days=look_back_history)

In [80]:
test_data_df = yh_data.get_hist_data_for_symbols(fx_table["Symbol"].to_list(), sd, ed, column="Close")

In [81]:
pca_result_test = pcatts.get_pca_ts(test_data_df)

pd.options.plotting.backend = "plotly"
pca_result_test.pca_ts_df.plot()

In [82]:
pca_result_test.res_ts_df.plot()

### Risk Allocation

In [107]:
risk_forecast = {
    "PCA1": 0,
    "PCA2": -1.0,
    "PCA3": 1.0,
    "PCA4": 1.0,
    "PCA5": -0.8,
    "PCA6": 0,
}

In [108]:
# configuration
vol_per_strategy = 2500
risk_allocation = {
    "PCA1": vol_per_strategy,
    "PCA2": vol_per_strategy,
    "PCA3": vol_per_strategy,
    "PCA4": vol_per_strategy,
    "PCA5": vol_per_strategy,
    "PCA6": vol_per_strategy,
}

In [109]:
risk_allocation = pd.Series(risk_allocation, name="pnl_vol").to_frame()

risk_allocation = risk_allocation.merge(pca_vol_year, left_index=True, right_index=True)
risk_allocation["notional"] = risk_allocation["pnl_vol"] / risk_allocation["vol"]

risk_allocation = risk_allocation.merge(
    pd.Series(risk_forecast, name="forecast").to_frame(),
    left_index=True,
    right_index=True,
)

In [110]:
risk_allocation["allocation"] = risk_allocation["notional"] * risk_allocation["forecast"]
risk_allocation.round(1)

      pnl_vol  vol  notional  forecast  allocation
PCA1     2500  0.2   10833.2       0.0         0.0
PCA2     2500  0.1   29376.2      -1.0    -29376.2
PCA3     2500  0.1   41794.9       1.0     41794.9
PCA4     2500  0.1   47500.0       1.0     47500.0
PCA5     2500  0.0   76528.6      -0.8    -61222.9
PCA6     2500  0.0  107365.0       0.0         0.0

In [111]:
pcatts.pca_mat[risk_allocation.index].dot(risk_allocation)["allocation"].round(0)

EURUSD   -22481.0
GBPUSD     5450.0
CHFUSD    59694.0
NOKUSD    35077.0
SEKUSD   -49812.0
SGDUSD   -28357.0
Name: allocation, dtype: float64

# Comments

* NOK is correlated with oil price, when oil price went up, oil company need to buy NOK to pay tax which push NOK stronger. However, after the central bank get money, it will get weak. 
* CHF is stronger due to the quality of the country especially lots of wealth people save money at swiss bank. It is positively correlated with China
* SEK get weak due to uncertainty of outlook, especially now it has conflicts with Russia
* GBP get strong due to more likely rate hiking to curb inflation
* EUR get strong if US rate cuts or get weak, if it get recession

In [74]:
time_index = pd.date_range("2023.01.01", "2023.01.05", freq="H")

In [84]:
a_ts = pd.Series(range(len(time_index)), index=time_index)