# Strategy Document

The second price pattern I noticed is for strong fundamental stocks. Here is the setup

* Both revenue and EPS has double growth over at least 2 digits.
* Price trend relatively strong.
* The business either has a Economic Moat, or link to a strong narrative of the whole market. like NVDA with economic moat, ANET link to the AI infra building.
* It is not the end of the cycle. Typically a new cycle growth will take at least two year.

For such stock, can just buy and hold until the cycle near peak which need keep track the expectation change from earning report history. The key part is to follow the industry and expectation release during the conference call.

In [1]:
import datetime as dt
import pandas as pd
import numpy as np
from sts.dio.equity import Ticker


class GrowthHalo:
    def __init__(
        self,
        symbol: str,
        high_growth_threshold: float = 0.2,
        medium_growth_ratio: float = 0.1,
        yearly_growth_sharpe: float = 2.0,
        quarterly_growth_sharpe: float = 1.0,
    ):
        self.symbol = symbol
        self.ticker = Ticker(symbol)
        self.high_growth_threshold = high_growth_threshold
        self.medium_growth_ratio = medium_growth_ratio
        self.yearly_growth_sharpe = yearly_growth_sharpe
        self.quarterly_growth_sharpe = quarterly_growth_sharpe

        self.init()

    def init(self):
        self.statement_quarterly = self.ticker.get_income_stmt(freq="quarterly").T.sort_index()
        self.statement_yearly = self.ticker.get_income_stmt(freq="yearly").T.sort_index()

        start = self.statement_yearly.index[0].strftime("%Y-%m-%d")
        end = dt.datetime.today().strftime("%Y-%m-%d")
        self.price_hist = self.ticker.history(start=start, end=end, interval="1d")

        self.statement_quarterly = pd.merge_asof(
            self.statement_quarterly,
            self.price_hist[["Close"]],
            left_index=True,
            right_index=True,
        )
        self.statement_yearly = pd.merge_asof(
            self.statement_yearly,
            self.price_hist[["Close"]],
            left_index=True,
            right_index=True,
        )

        self.statement_quarterly["PE"] = (
            self.statement_quarterly["Close"] / self.statement_quarterly["DilutedEPS"] / 4.0
        )
        self.statement_yearly["PE"] = self.statement_yearly["Close"] / self.statement_yearly["DilutedEPS"]

    def __repr__(self):
        return f"GrowthHalo for ticker: %s" % (self.symbol)

    @property
    def EPS_quarterly(self):
        return self.statement_quarterly["DilutedEPS"]

    @property
    def EPS_yearly(self):
        return self.statement_yearly["DilutedEPS"]

    @property
    def OperatingRevenue_quarterly(self):
        return self.statement_quarterly["OperatingRevenue"]

    @property
    def OperatingRevenue_yearly(self):
        return self.statement_yearly["OperatingRevenue"]

    @property
    def eps_yearly_growth(self):
        return self.EPS_yearly / self.EPS_yearly.shift() - 1.0

    @property
    def eps_quarterly_growth(self):
        return self.EPS_quarterly / self.EPS_quarterly.shift() - 1.0

    @property
    def OperatingRevenue_yearly_growth(self):
        return self.OperatingRevenue_yearly / self.OperatingRevenue_yearly.shift() - 1.0

    @property
    def OperatingRevenue_quarterly_growth(self):
        return self.OperatingRevenue_quarterly / self.OperatingRevenue_quarterly.shift() - 1.0

    @property
    def pe_yearly(self):
        return self.statement_yearly["PE"]

    @property
    def pe_quarterly(self):
        return self.statement_quarterly["PE"]

    def sharpe_mod_ratio(self, growth_history: pd.Series) -> float:
        mean = growth_history.mean()
        diff = np.minimum(0, growth_history.diff().dropna())  # only care about downside move
        std = np.sqrt(np.mean(diff * diff))
        if std < 1e-8:
            return 100
        else:
            return mean / std

    def get_growth_aspect(self):
        """
        the bigger the number, the better
        """
        eps_growth_yearly = self.eps_yearly_growth.dropna()
        eps_growth_quarterly = self.eps_quarterly_growth.dropna() * 4.0  # scale to annual number

        if (
            (eps_growth_yearly.mean() >= self.high_growth_threshold)
            and (self.sharpe_mod_ratio(eps_growth_quarterly) >= self.quarterly_growth_sharpe)
            and np.all(eps_growth_quarterly > 0)
        ):
            if eps_growth_quarterly.mean() >= self.high_growth_threshold:  # still on expension
                return 2.0
            elif eps_growth_quarterly.mean() >= self.medium_growth_ratio:  # around the peak of the cycle
                return 1.0
            else:
                return 0.0  # typically means the end of the cycle
        else:
            return 0.0

In [2]:
from sts.dio.symbols import sp500_symbol_table
from sts.utils.logging import get_logger, logging

logger = get_logger("GrowthHalo", logging.INFO)

In [3]:
growth_scan_df = None
for sym in sp500_symbol_table.to_symbol():
    try:
        logger.info(sym)
        sym_growth_halo = GrowthHalo(sym.YahooSym, yearly_growth_sharpe=1.5, quarterly_growth_sharpe=0.8)
        if sym_growth_halo.get_growth_aspect() > 0:
            logger.info("adding %s" % (sym.YahooSym))
            df2 = sym_growth_halo.eps_yearly_growth.dropna()
            df3 = sym_growth_halo.pe_yearly.dropna()
            df = pd.DataFrame(
                {
                    "sym": sym.YahooSym,
                    "EPS": df2,
                    "PE": df3,
                    "GrowthHalo": sym_growth_halo,
                }
            )
            growth_scan_df = pd.concat([growth_scan_df, df])
    except Exception as e:
        logger.error(str(e))

2024-11-20 21:27:21,615 - GrowthHalo - INFO - MMM
2024-11-20 21:27:22,440 - GrowthHalo - INFO - AOS
2024-11-20 21:27:23,076 - GrowthHalo - INFO - ABT
2024-11-20 21:27:23,739 - GrowthHalo - INFO - ABBV
2024-11-20 21:27:24,429 - GrowthHalo - INFO - ACN
2024-11-20 21:27:24,998 - GrowthHalo - INFO - ATVI
2024-11-20 21:27:25,236 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:27:25,238 - GrowthHalo - INFO - ADM
2024-11-20 21:27:25,953 - GrowthHalo - INFO - ADBE
2024-11-20 21:27:26,550 - GrowthHalo - INFO - ADP
2024-11-20 21:27:27,250 - GrowthHalo - INFO - AAP
2024-11-20 21:27:27,846 - GrowthHalo - INFO - AES
2024-11-20 21:27:28,454 - GrowthHalo - INFO - AFL
2024-11-20 21:27:29,068 - GrowthHalo - INFO - A
2024-11-20 21:27:29,693 - GrowthHalo - INFO - APD
2024-11-20 21:27:30,286 - GrowthHalo - INFO - AKAM
2024-11-20 21:27:30,942 - GrowthHalo - INFO - ALK
2024-11-20 21:27:31,620 - GrowthHalo - INFO - ALB
2024-11-20 21:27:32,280 - GrowthHalo - INFO - ARE
2024-11-20 21:27:32,946 - GrowthHalo - INFO - ALGN
2024-11-20 21:27:33,536 - GrowthHalo - INFO - ALLE
2024-11-20 21:27:34,156 - GrowthHalo - INFO - adding ALLE
2024-11-20 21:27:34,166 - GrowthHalo - INFO - LNT
2024-11-20 21:27:34,769 - GrowthHalo - INFO - ALL
2024-11-20 21:27:35,432 - GrowthHalo - INFO - GOOGL
2024-11-20 21:27:36,133 - GrowthHalo - INFO - GOOG
2024-11-20 21:27:36,748 - GrowthHalo - INFO - MO
2024-11-20 21:27:37,389 - GrowthHalo - INFO - AMZN
2024-11-20 21:27:37,971 - GrowthHalo - INFO - AMCR
2024-11-20 21:27:38,537 - GrowthHalo - INFO - AMD
2024-11-20 21:27:39,122 - GrowthHalo - INFO - AEE
2024-11-20 21:27:39,757 - GrowthHalo - INFO - AAL
2024-11-20 21:27:40,300 - GrowthHalo - INFO - AEP
2024-11-20 21:27:40,998 - GrowthHalo - INFO - AXP
2024-11-20 21:27:41,557 - GrowthHalo - INFO - AIG
2024-11-20 21:27:42,179 - GrowthHalo - INFO - AMT
2024-11-20 21:27:43,865 - GrowthHalo - INFO - AWK
2024-11-20 21:27:44,469 - GrowthHalo - INFO - AMP
2024-11-20 21:27:45,055 - GrowthHalo - INFO - ABC
2024-11-20 21:27:45,293 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:27:45,295 - GrowthHalo - INFO - AME
2024-11-20 21:27:45,985 - GrowthHalo - INFO - AMGN
2024-11-20 21:27:46,652 - GrowthHalo - INFO - APH
2024-11-20 21:27:47,282 - GrowthHalo - INFO - ADI
2024-11-20 21:27:47,827 - GrowthHalo - INFO - ANSS
2024-11-20 21:27:48,336 - GrowthHalo - INFO - AON
2024-11-20 21:27:48,983 - GrowthHalo - INFO - APA
2024-11-20 21:27:49,658 - GrowthHalo - INFO - AAPL
2024-11-20 21:27:50,188 - GrowthHalo - INFO - AMAT
2024-11-20 21:27:50,766 - GrowthHalo - INFO - APTV
2024-11-20 21:27:51,412 - GrowthHalo - INFO - ACGL
2024-11-20 21:27:51,928 - GrowthHalo - INFO - ANET
2024-11-20 21:27:52,525 - GrowthHalo - INFO - adding ANET
2024-11-20 21:27:52,528 - GrowthHalo - INFO - AJG
2024-11-20 21:27:53,139 - GrowthHalo - INFO - AIZ
2024-11-20 21:27:53,702 - GrowthHalo - INFO - T
2024-11-20 21:27:54,358 - GrowthHalo - INFO - ATO
2024-11-20 21:27:55,021 - GrowthHalo - INFO - ADSK
2024-11-20 21:27:55,595 - GrowthHalo - INFO - AZO
2024-11-20 21:27:56,105 - GrowthHalo - INFO - AVB
2024-11-20 21:27:56,703 - GrowthHalo - INFO - AVY
2024-11-20 21:27:57,310 - GrowthHalo - INFO - AXON
2024-11-20 21:27:57,853 - GrowthHalo - INFO - BKR
2024-11-20 21:27:58,388 - GrowthHalo - INFO - BALL
2024-11-20 21:27:59,035 - GrowthHalo - INFO - BAC
2024-11-20 21:27:59,649 - GrowthHalo - INFO - BBWI
2024-11-20 21:28:00,403 - GrowthHalo - INFO - BAX
2024-11-20 21:28:01,092 - GrowthHalo - INFO - BDX
2024-11-20 21:28:01,798 - GrowthHalo - INFO - WRB
2024-11-20 21:28:02,366 - GrowthHalo - INFO - BRK.B
2024-11-20 21:28:02,604 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:28:02,606 - GrowthHalo - INFO - BBY
2024-11-20 21:28:04,402 - GrowthHalo - INFO - BIO
2024-11-20 21:28:05,142 - GrowthHalo - INFO - TECH
2024-11-20 21:28:05,753 - GrowthHalo - INFO - BIIB
2024-11-20 21:28:06,536 - GrowthHalo - INFO - BLK
2024-11-20 21:28:07,268 - GrowthHalo - INFO - BK
2024-11-20 21:28:07,790 - GrowthHalo - INFO - BA
2024-11-20 21:28:08,442 - GrowthHalo - INFO - BKNG
2024-11-20 21:28:08,930 - GrowthHalo - INFO - BWA
2024-11-20 21:28:09,563 - GrowthHalo - INFO - BXP
2024-11-20 21:28:10,139 - GrowthHalo - INFO - BSX
2024-11-20 21:28:10,654 - GrowthHalo - INFO - BMY
2024-11-20 21:28:11,420 - GrowthHalo - INFO - AVGO
2024-11-20 21:28:12,018 - GrowthHalo - INFO - BR
2024-11-20 21:28:12,497 - GrowthHalo - INFO - BRO
2024-11-20 21:28:13,046 - GrowthHalo - INFO - BF.B
2024-11-20 21:28:13,378 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:28:13,380 - GrowthHalo - INFO - BG
2024-11-20 21:28:13,996 - GrowthHalo - INFO - CHRW
2024-11-20 21:28:14,530 - GrowthHalo - INFO - CDNS
2024-11-20 21:28:15,122 - GrowthHalo - INFO - CZR
2024-11-20 21:28:15,763 - GrowthHalo - INFO - CPT
2024-11-20 21:28:16,379 - GrowthHalo - INFO - CPB
2024-11-20 21:28:16,986 - GrowthHalo - INFO - COF
2024-11-20 21:28:17,693 - GrowthHalo - INFO - CAH
2024-11-20 21:28:18,317 - GrowthHalo - INFO - KMX
2024-11-20 21:28:18,893 - GrowthHalo - INFO - CCL
2024-11-20 21:28:19,562 - GrowthHalo - INFO - CARR
2024-11-20 21:28:20,135 - GrowthHalo - INFO - CTLT
2024-11-20 21:28:20,714 - GrowthHalo - INFO - CAT
2024-11-20 21:28:21,329 - GrowthHalo - INFO - CBOE
2024-11-20 21:28:21,955 - GrowthHalo - INFO - CBRE
2024-11-20 21:28:22,654 - GrowthHalo - INFO - CDW
2024-11-20 21:28:23,212 - GrowthHalo - INFO - CE
2024-11-20 21:28:23,913 - GrowthHalo - INFO - CNC
2024-11-20 21:28:24,493 - GrowthHalo - INFO - CNP
2024-11-20 21:28:26,205 - GrowthHalo - INFO - CDAY
2024-11-20 21:28:26,433 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:28:26,435 - GrowthHalo - INFO - CF
2024-11-20 21:28:27,101 - GrowthHalo - INFO - CRL
2024-11-20 21:28:27,675 - GrowthHalo - INFO - SCHW
2024-11-20 21:28:28,311 - GrowthHalo - INFO - CHTR
2024-11-20 21:28:28,867 - GrowthHalo - INFO - CVX
2024-11-20 21:28:29,484 - GrowthHalo - INFO - CMG
2024-11-20 21:28:30,102 - GrowthHalo - INFO - CB
2024-11-20 21:28:30,767 - GrowthHalo - INFO - CHD
2024-11-20 21:28:31,262 - GrowthHalo - INFO - CI
2024-11-20 21:28:31,912 - GrowthHalo - INFO - CINF
2024-11-20 21:28:32,517 - GrowthHalo - INFO - CTAS
2024-11-20 21:28:33,081 - GrowthHalo - INFO - CSCO
2024-11-20 21:28:33,628 - GrowthHalo - INFO - C
2024-11-20 21:28:34,195 - GrowthHalo - INFO - CFG
2024-11-20 21:28:34,871 - GrowthHalo - INFO - CLX
2024-11-20 21:28:35,423 - GrowthHalo - INFO - CME
2024-11-20 21:28:35,977 - GrowthHalo - INFO - CMS
2024-11-20 21:28:36,594 - GrowthHalo - INFO - KO
2024-11-20 21:28:37,221 - GrowthHalo - INFO - CTSH
2024-11-20 21:28:37,821 - GrowthHalo - INFO - CL
2024-11-20 21:28:38,559 - GrowthHalo - INFO - CMCSA
2024-11-20 21:28:39,175 - GrowthHalo - INFO - CMA
2024-11-20 21:28:39,739 - GrowthHalo - INFO - CAG
2024-11-20 21:28:40,442 - GrowthHalo - INFO - COP
2024-11-20 21:28:41,067 - GrowthHalo - INFO - ED
2024-11-20 21:28:41,668 - GrowthHalo - INFO - STZ
2024-11-20 21:28:42,290 - GrowthHalo - INFO - CEG
2024-11-20 21:28:42,852 - GrowthHalo - INFO - COO
2024-11-20 21:28:43,627 - GrowthHalo - INFO - CPRT
2024-11-20 21:28:44,197 - GrowthHalo - INFO - GLW
2024-11-20 21:28:44,784 - GrowthHalo - INFO - CTVA
2024-11-20 21:28:45,404 - GrowthHalo - INFO - CSGP
2024-11-20 21:28:45,969 - GrowthHalo - INFO - COST
2024-11-20 21:28:47,675 - GrowthHalo - INFO - CTRA
2024-11-20 21:28:48,380 - GrowthHalo - INFO - CCI
2024-11-20 21:28:49,027 - GrowthHalo - INFO - CSX
2024-11-20 21:28:49,823 - GrowthHalo - INFO - CMI
2024-11-20 21:28:50,464 - GrowthHalo - INFO - CVS
2024-11-20 21:28:51,082 - GrowthHalo - INFO - DHI
2024-11-20 21:28:51,702 - GrowthHalo - INFO - DHR
2024-11-20 21:28:52,359 - GrowthHalo - INFO - DRI
2024-11-20 21:28:52,916 - GrowthHalo - INFO - DVA
2024-11-20 21:28:53,494 - GrowthHalo - INFO - DE
2024-11-20 21:28:54,069 - GrowthHalo - INFO - DAL
2024-11-20 21:28:54,681 - GrowthHalo - INFO - XRAY
2024-11-20 21:28:55,312 - GrowthHalo - INFO - DVN
2024-11-20 21:28:55,921 - GrowthHalo - INFO - DXCM
2024-11-20 21:28:56,541 - GrowthHalo - INFO - FANG
2024-11-20 21:28:57,055 - GrowthHalo - INFO - DLR
2024-11-20 21:28:57,704 - GrowthHalo - INFO - DFS
2024-11-20 21:28:58,246 - GrowthHalo - INFO - DIS
2024-11-20 21:28:58,973 - GrowthHalo - INFO - DG
2024-11-20 21:28:59,486 - GrowthHalo - INFO - DLTR
2024-11-20 21:28:59,984 - GrowthHalo - INFO - D
2024-11-20 21:29:00,617 - GrowthHalo - INFO - DPZ
2024-11-20 21:29:01,183 - GrowthHalo - INFO - DOV
2024-11-20 21:29:01,786 - GrowthHalo - INFO - DOW
2024-11-20 21:29:02,347 - GrowthHalo - INFO - DTE
2024-11-20 21:29:03,046 - GrowthHalo - INFO - DUK
2024-11-20 21:29:03,708 - GrowthHalo - INFO - DD
2024-11-20 21:29:04,394 - GrowthHalo - INFO - DXC
2024-11-20 21:29:05,109 - GrowthHalo - INFO - EMN
2024-11-20 21:29:05,747 - GrowthHalo - INFO - ETN
2024-11-20 21:29:06,426 - GrowthHalo - INFO - EBAY
2024-11-20 21:29:07,056 - GrowthHalo - INFO - ECL
2024-11-20 21:29:07,684 - GrowthHalo - INFO - EIX
2024-11-20 21:29:09,432 - GrowthHalo - INFO - EW
2024-11-20 21:29:10,067 - GrowthHalo - INFO - EA
2024-11-20 21:29:10,688 - GrowthHalo - INFO - ELV
2024-11-20 21:29:11,286 - GrowthHalo - INFO - LLY
2024-11-20 21:29:11,894 - GrowthHalo - INFO - EMR
2024-11-20 21:29:12,472 - GrowthHalo - INFO - ENPH
2024-11-20 21:29:13,022 - GrowthHalo - INFO - ETR
2024-11-20 21:29:13,590 - GrowthHalo - INFO - EOG
2024-11-20 21:29:14,257 - GrowthHalo - INFO - EPAM
2024-11-20 21:29:14,833 - GrowthHalo - INFO - EQT
2024-11-20 21:29:15,445 - GrowthHalo - INFO - EFX
2024-11-20 21:29:16,066 - GrowthHalo - INFO - EQIX
2024-11-20 21:29:16,639 - GrowthHalo - INFO - EQR
2024-11-20 21:29:17,238 - GrowthHalo - INFO - ESS
2024-11-20 21:29:17,916 - GrowthHalo - INFO - EL
2024-11-20 21:29:18,497 - GrowthHalo - INFO - ETSY
2024-11-20 21:29:19,115 - GrowthHalo - INFO - EG
2024-11-20 21:29:19,694 - GrowthHalo - INFO - EVRG
2024-11-20 21:29:20,293 - GrowthHalo - INFO - ES
2024-11-20 21:29:20,942 - GrowthHalo - INFO - EXC
2024-11-20 21:29:21,670 - GrowthHalo - INFO - EXPE
2024-11-20 21:29:22,333 - GrowthHalo - INFO - EXPD
2024-11-20 21:29:22,909 - GrowthHalo - INFO - EXR
2024-11-20 21:29:23,515 - GrowthHalo - INFO - XOM
2024-11-20 21:29:24,225 - GrowthHalo - INFO - FFIV
2024-11-20 21:29:24,847 - GrowthHalo - INFO - FDS
2024-11-20 21:29:25,415 - GrowthHalo - INFO - FICO
2024-11-20 21:29:25,999 - GrowthHalo - INFO - FAST
2024-11-20 21:29:26,640 - GrowthHalo - INFO - FRT
2024-11-20 21:29:27,231 - GrowthHalo - INFO - FDX
2024-11-20 21:29:27,862 - GrowthHalo - INFO - FITB
2024-11-20 21:29:28,461 - GrowthHalo - INFO - FSLR
2024-11-20 21:29:29,134 - GrowthHalo - INFO - FE
2024-11-20 21:29:29,776 - GrowthHalo - INFO - FIS
2024-11-20 21:29:30,344 - GrowthHalo - INFO - FI
2024-11-20 21:29:30,851 - GrowthHalo - INFO - FLT
2024-11-20 21:29:31,100 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:29:31,101 - GrowthHalo - INFO - FMC
2024-11-20 21:29:31,744 - GrowthHalo - INFO - F
2024-11-20 21:29:32,377 - GrowthHalo - INFO - FTNT
2024-11-20 21:29:33,965 - GrowthHalo - INFO - FTV
2024-11-20 21:29:34,606 - GrowthHalo - INFO - FOXA
2024-11-20 21:29:35,172 - GrowthHalo - INFO - FOX
2024-11-20 21:29:35,773 - GrowthHalo - INFO - BEN
2024-11-20 21:29:36,482 - GrowthHalo - INFO - FCX
2024-11-20 21:29:36,999 - GrowthHalo - INFO - GRMN
2024-11-20 21:29:37,640 - GrowthHalo - INFO - IT
2024-11-20 21:29:38,245 - GrowthHalo - INFO - adding IT
2024-11-20 21:29:38,249 - GrowthHalo - INFO - GEHC
2024-11-20 21:29:38,711 - GrowthHalo - INFO - GEN
2024-11-20 21:29:39,414 - GrowthHalo - INFO - GNRC
2024-11-20 21:29:40,069 - GrowthHalo - INFO - GD
2024-11-20 21:29:40,711 - GrowthHalo - INFO - GE
2024-11-20 21:29:41,382 - GrowthHalo - INFO - GIS
2024-11-20 21:29:41,971 - GrowthHalo - INFO - GM
2024-11-20 21:29:42,507 - GrowthHalo - INFO - GPC
2024-11-20 21:29:43,146 - GrowthHalo - INFO - GILD
2024-11-20 21:29:43,655 - GrowthHalo - INFO - GL
2024-11-20 21:29:44,287 - GrowthHalo - INFO - GPN
2024-11-20 21:29:44,904 - GrowthHalo - INFO - GS
2024-11-20 21:29:45,635 - GrowthHalo - INFO - HAL
2024-11-20 21:29:46,204 - GrowthHalo - INFO - HIG
2024-11-20 21:29:46,827 - GrowthHalo - INFO - HAS
2024-11-20 21:29:47,465 - GrowthHalo - INFO - HCA
2024-11-20 21:29:48,037 - GrowthHalo - INFO - PEAK
2024-11-20 21:29:48,353 - GrowthHalo - ERROR - index 0 is out of bounds for axis 0 with size 0
2024-11-20 21:29:48,354 - GrowthHalo - INFO - HSIC
2024-11-20 21:29:48,979 - GrowthHalo - INFO - HSY
2024-11-20 21:29:49,647 - GrowthHalo - INFO - HES
2024-11-20 21:29:50,232 - GrowthHalo - INFO - HPE
2024-11-20 21:29:50,836 - GrowthHalo - INFO - HLT
2024-11-20 21:29:51,379 - GrowthHalo - INFO - HOLX
2024-11-20 21:29:51,958 - GrowthHalo - INFO - HD
2024-11-20 21:29:52,517 - GrowthHalo - INFO - HON
2024-11-20 21:29:53,161 - GrowthHalo - INFO - HRL
2024-11-20 21:29:53,840 - GrowthHalo - INFO - HST
2024-11-20 21:29:54,489 - GrowthHalo - INFO - HWM
2024-11-20 21:29:55,198 - GrowthHalo - INFO - adding HWM
2024-11-20 21:29:55,201 - GrowthHalo - INFO - HPQ
2024-11-20 21:29:55,858 - GrowthHalo - INFO - HUM
2024-11-20 21:29:56,459 - GrowthHalo - INFO - HBAN
2024-11-20 21:29:57,150 - GrowthHalo - INFO - HII
2024-11-20 21:29:57,818 - GrowthHalo - INFO - IBM
2024-11-20 21:29:58,577 - GrowthHalo - INFO - IEX
2024-11-20 21:29:59,249 - GrowthHalo - INFO - IDXX
2024-11-20 21:29:59,878 - GrowthHalo - INFO - ITW
2024-11-20 21:30:00,423 - GrowthHalo - INFO - ILMN
2024-11-20 21:30:01,001 - GrowthHalo - INFO - INCY
2024-11-20 21:30:01,643 - GrowthHalo - INFO - IR
2024-11-20 21:30:02,300 - GrowthHalo - INFO - PODD
2024-11-20 21:30:02,886 - GrowthHalo - INFO - INTC
2024-11-20 21:30:03,481 - GrowthHalo - INFO - ICE
2024-11-20 21:30:04,134 - GrowthHalo - INFO - IFF
2024-11-20 21:30:04,692 - GrowthHalo - INFO - IP
2024-11-20 21:30:05,365 - GrowthHalo - INFO - IPG
2024-11-20 21:30:05,983 - GrowthHalo - INFO - INTU
2024-11-20 21:30:06,655 - GrowthHalo - INFO - ISRG
2024-11-20 21:30:07,275 - GrowthHalo - INFO - IVZ
2024-11-20 21:30:07,927 - GrowthHalo - INFO - INVH
2024-11-20 21:30:08,535 - GrowthHalo - INFO - IQV
2024-11-20 21:30:09,098 - GrowthHalo - INFO - IRM
2024-11-20 21:30:09,797 - GrowthHalo - INFO - JBHT
2024-11-20 21:30:10,410 - GrowthHalo - INFO - JKHY
2024-11-20 21:30:10,973 - GrowthHalo - INFO - J
2024-11-20 21:30:11,521 - GrowthHalo - INFO - JNJ
2024-11-20 21:30:12,093 - GrowthHalo - INFO - JCI
2024-11-20 21:30:12,713 - GrowthHalo - INFO - JPM
2024-11-20 21:30:13,347 - GrowthHalo - INFO - JNPR
2024-11-20 21:30:13,946 - GrowthHalo - INFO - K
2024-11-20 21:30:14,558 - GrowthHalo - INFO - KDP
2024-11-20 21:30:15,204 - GrowthHalo - INFO - KEY
2024-11-20 21:30:15,959 - GrowthHalo - INFO - KEYS
2024-11-20 21:30:16,530 - GrowthHalo - INFO - KMB
2024-11-20 21:30:17,173 - GrowthHalo - INFO - KIM
2024-11-20 21:30:17,818 - GrowthHalo - INFO - KMI
2024-11-20 21:30:18,480 - GrowthHalo - INFO - KLAC
2024-11-20 21:30:19,102 - GrowthHalo - INFO - KHC
2024-11-20 21:30:19,682 - GrowthHalo - INFO - KR
2024-11-20 21:30:20,335 - GrowthHalo - INFO - LHX
2024-11-20 21:30:20,938 - GrowthHalo - INFO - LH
2024-11-20 21:30:21,609 - GrowthHalo - INFO - LRCX
2024-11-20 21:30:22,257 - GrowthHalo - INFO - LW
2024-11-20 21:30:22,870 - GrowthHalo - INFO - LVS
2024-11-20 21:30:23,574 - GrowthHalo - INFO - LDOS
2024-11-20 21:30:24,324 - GrowthHalo - INFO - LEN
2024-11-20 21:30:24,958 - GrowthHalo - INFO - LNC
2024-11-20 21:30:25,557 - GrowthHalo - INFO - LIN
2024-11-20 21:30:26,225 - GrowthHalo - INFO - LYV
2024-11-20 21:30:26,831 - GrowthHalo - INFO - LKQ
2024-11-20 21:30:27,423 - GrowthHalo - INFO - LMT
2024-11-20 21:30:28,047 - GrowthHalo - INFO - L
2024-11-20 21:30:28,633 - GrowthHalo - INFO - LOW
2024-11-20 21:30:29,225 - GrowthHalo - INFO - LYB
2024-11-20 21:30:29,849 - GrowthHalo - INFO - adding LYB
2024-11-20 21:30:29,852 - GrowthHalo - INFO - MTB
2024-11-20 21:30:30,535 - GrowthHalo - INFO - MRO
2024-11-20 21:30:31,259 - GrowthHalo - INFO - MPC
2024-11-20 21:30:31,983 - GrowthHalo - INFO - MKTX
2024-11-20 21:30:32,596 - GrowthHalo - INFO - MAR
2024-11-20 21:30:33,187 - GrowthHalo - INFO - MMC
2024-11-20 21:30:33,849 - GrowthHalo - INFO - MLM
2024-11-20 21:30:34,489 - GrowthHalo - INFO - MAS
2024-11-20 21:30:35,121 - GrowthHalo - INFO - MA
2024-11-20 21:30:35,762 - GrowthHalo - INFO - MTCH
2024-11-20 21:30:36,384 - GrowthHalo - INFO - MKC
2024-11-20 21:30:36,975 - GrowthHalo - INFO - MCD
2024-11-20 21:30:37,628 - GrowthHalo - INFO - MCK
2024-11-20 21:30:38,294 - GrowthHalo - INFO - MDT
2024-11-20 21:30:38,896 - GrowthHalo - INFO - MRK
2024-11-20 21:30:39,538 - GrowthHalo - INFO - META
2024-11-20 21:30:40,178 - GrowthHalo - INFO - MET
2024-11-20 21:30:40,808 - GrowthHalo - INFO - MTD
2024-11-20 21:30:41,387 - GrowthHalo - INFO - MGM
2024-11-20 21:30:42,034 - GrowthHalo - INFO - MCHP
2024-11-20 21:30:42,672 - GrowthHalo - INFO - MU
2024-11-20 21:30:43,257 - GrowthHalo - INFO - MSFT
2024-11-20 21:30:43,880 - GrowthHalo - INFO - MAA
2024-11-20 21:30:44,469 - GrowthHalo - INFO - MRNA
2024-11-20 21:30:45,218 - GrowthHalo - INFO - MHK
2024-11-20 21:30:45,769 - GrowthHalo - INFO - MOH
2024-11-20 21:30:46,406 - GrowthHalo - INFO - TAP
2024-11-20 21:30:47,102 - GrowthHalo - INFO - MDLZ
2024-11-20 21:30:47,855 - GrowthHalo - INFO - MPWR
2024-11-20 21:30:48,486 - GrowthHalo - INFO - MNST
2024-11-20 21:30:49,053 - GrowthHalo - INFO - MCO
2024-11-20 21:30:49,719 - GrowthHalo - INFO - MS
2024-11-20 21:30:50,299 - GrowthHalo - INFO - MOS
2024-11-20 21:30:50,874 - GrowthHalo - INFO - MSI
2024-11-20 21:30:51,429 - GrowthHalo - INFO - MSCI
2024-11-20 21:30:51,968 - GrowthHalo - INFO - NDAQ
2024-11-20 21:30:52,572 - GrowthHalo - INFO - NTAP
2024-11-20 21:30:53,095 - GrowthHalo - INFO - NFLX
2024-11-20 21:30:53,755 - GrowthHalo - INFO - NWL
2024-11-20 21:30:54,355 - GrowthHalo - INFO - NEM
2024-11-20 21:30:54,930 - GrowthHalo - INFO - NWSA
2024-11-20 21:30:55,561 - GrowthHalo - INFO - NWS
2024-11-20 21:30:56,274 - GrowthHalo - INFO - NEE
2024-11-20 21:30:56,908 - GrowthHalo - INFO - NKE
2024-11-20 21:30:57,474 - GrowthHalo - INFO - NI
2024-11-20 21:30:58,090 - GrowthHalo - INFO - NDSN
2024-11-20 21:30:58,698 - GrowthHalo - INFO - NSC
2024-11-20 21:30:59,370 - GrowthHalo - INFO - NTRS
2024-11-20 21:30:59,940 - GrowthHalo - INFO - NOC
2024-11-20 21:31:00,503 - GrowthHalo - INFO - NCLH
2024-11-20 21:31:01,031 - GrowthHalo - INFO - NRG
2024-11-20 21:31:01,559 - GrowthHalo - INFO - NUE
2024-11-20 21:31:02,274 - GrowthHalo - INFO - NVDA
2024-11-20 21:31:02,944 - GrowthHalo - INFO - NVR
2024-11-20 21:31:03,525 - GrowthHalo - INFO - NXPI
2024-11-20 21:31:04,302 - GrowthHalo - INFO - ORLY
2024-11-20 21:31:04,905 - GrowthHalo - INFO - OXY
2024-11-20 21:31:05,547 - GrowthHalo - INFO - ODFL
2024-11-20 21:31:06,186 - GrowthHalo - INFO - OMC
2024-11-20 21:31:06,773 - GrowthHalo - INFO - ON
2024-11-20 21:31:07,426 - GrowthHalo - INFO - OKE
2024-11-20 21:31:08,103 - GrowthHalo - INFO - ORCL
2024-11-20 21:31:08,729 - GrowthHalo - INFO - OGN
2024-11-20 21:31:09,277 - GrowthHalo - INFO - OTIS
2024-11-20 21:31:09,835 - GrowthHalo - INFO - PCAR
2024-11-20 21:31:10,463 - GrowthHalo - INFO - PKG
2024-11-20 21:31:11,074 - GrowthHalo - INFO - PANW
2024-11-20 21:31:11,666 - GrowthHalo - INFO - PARA
2024-11-20 21:31:12,272 - GrowthHalo - ERROR - float division by zero
2024-11-20 21:31:12,273 - GrowthHalo - INFO - PH
2024-11-20 21:31:12,871 - GrowthHalo - INFO - PAYX
2024-11-20 21:31:13,542 - GrowthHalo - INFO - PAYC
2024-11-20 21:31:14,353 - GrowthHalo - INFO - PYPL
2024-11-20 21:31:14,902 - GrowthHalo - INFO - PNR
2024-11-20 21:31:15,518 - GrowthHalo - INFO - PEP
2024-11-20 21:31:16,199 - GrowthHalo - INFO - PFE
2024-11-20 21:31:16,836 - GrowthHalo - INFO - PCG
2024-11-20 21:31:17,478 - GrowthHalo - INFO - PM
2024-11-20 21:31:18,066 - GrowthHalo - INFO - PSX
2024-11-20 21:31:18,660 - GrowthHalo - INFO - PNW
2024-11-20 21:31:19,308 - GrowthHalo - INFO - PXD

In [5]:
min_growth_sym = growth_scan_df.groupby("sym")["EPS"].min()
min_growth_sym[min_growth_sym > 0]

sym
ANET    0.316646
IT      0.081433
SBAC    0.092417
URI     0.189882
Name: EPS, dtype: object

In [6]:
growth_scan_df

             sym       EPS           PE                   GrowthHalo
2020-12-31  ALLE       NaN    32.651013  GrowthHalo for ticker: ALLE
2021-12-31  ALLE  0.575221    23.848694  GrowthHalo for ticker: ALLE
2022-12-31  ALLE  -0.02809    19.738465  GrowthHalo for ticker: ALLE
2023-12-31  ALLE  0.179191    20.474453  GrowthHalo for ticker: ALLE
2020-12-31  ANET       NaN    36.366709  GrowthHalo for ticker: ANET
2021-12-31  ANET  0.316646    54.657795  GrowthHalo for ticker: ANET
2022-12-31  ANET  0.623574    28.419203  GrowthHalo for ticker: ANET
2023-12-31  ANET  0.540984    35.791792  GrowthHalo for ticker: ANET
2020-12-31    IT       NaN    54.118244    GrowthHalo for ticker: IT
2021-12-31    IT  2.111486    36.299675    GrowthHalo for ticker: IT
2022-12-31    IT  0.081433    33.748997    GrowthHalo for ticker: IT
2023-12-31    IT   0.11245    40.713898    GrowthHalo for ticker: IT
2020-12-31   HWM       NaN    47.846894   GrowthHalo for ticker: HWM
2021-12-31   HWM       0.0    53.432432   GrowthHalo for ticker: HWM
2022-12-31   HWM  0.881356    35.264127   GrowthHalo for ticker: HWM
2023-12-31   HWM  0.648649    29.483689   GrowthHalo for ticker: HWM
2020-12-31   LYB       NaN    17.160482   GrowthHalo for ticker: LYB
2021-12-31   LYB  2.950472     4.563979   GrowthHalo for ticker: LYB
2022-12-31   LYB -0.294925     6.409581   GrowthHalo for ticker: LYB
2023-12-31   LYB -0.453006    14.143414   GrowthHalo for ticker: LYB
2020-12-31  SBAC       NaN  1278.290957  GrowthHalo for ticker: SBAC
2021-12-31  SBAC  9.190476   174.302074  GrowthHalo for ticker: SBAC
2022-12-31  SBAC  0.971963     64.25991  GrowthHalo for ticker: SBAC
2023-12-31  SBAC  0.092417    54.027979  GrowthHalo for ticker: SBAC
2020-12-31   URI       NaN    18.575108   GrowthHalo for ticker: URI
2021-12-31   URI  0.560656    17.053833   GrowthHalo for ticker: URI
2022-12-31   URI  0.557248    11.713559   GrowthHalo for ticker: URI
2023-12-31   URI  0.189882     16.10701   GrowthHalo for ticker: URI
2020-12-31   XYL       NaN    69.610519   GrowthHalo for ticker: XYL
2021-12-31   XYL  0.678571     49.32262   GrowthHalo for ticker: XYL
2022-12-31   XYL -0.165957    55.235333   GrowthHalo for ticker: XYL
2023-12-31   XYL  0.423469     40.65534   GrowthHalo for ticker: XYL

In [43]:
growth_scan_df = growth_scan_df[growth_scan_df["sym"].isin(min_growth_sym[min_growth_sym > 0].index)]

In [44]:
growth_scan_df

             sym       EPS          PE                   GrowthHalo
2020-12-31  ANET       NaN   36.366709  GrowthHalo for ticker: ANET
2021-12-31  ANET  0.316646   54.657795  GrowthHalo for ticker: ANET
2022-12-31  ANET  0.623574   28.419203  GrowthHalo for ticker: ANET
2023-12-31  ANET  0.540984   35.791792  GrowthHalo for ticker: ANET
2020-12-31  FTNT       NaN    51.21724  GrowthHalo for ticker: FTNT
2021-12-31  FTNT  0.258621    98.46575  GrowthHalo for ticker: FTNT
2022-12-31  FTNT  0.452055   46.122641  GrowthHalo for ticker: FTNT
2023-12-31  FTNT  0.377358    40.08904  GrowthHalo for ticker: FTNT
2020-12-31   RSG       NaN   30.273367   GrowthHalo for ticker: RSG
2021-12-31   RSG  0.337748    33.27242   GrowthHalo for ticker: RSG
2022-12-31   RSG  0.160891   26.894738   GrowthHalo for ticker: RSG
2023-12-31   RSG  0.166311   29.894046   GrowthHalo for ticker: RSG
2020-12-31   NOW       NaN  932.932191   GrowthHalo for ticker: NOW
2021-12-31   NOW  0.915254  574.433615   GrowthHalo for ticker: NOW
2022-12-31   NOW  0.415929  242.668743   GrowthHalo for ticker: NOW
2023-12-31   NOW    4.2625   83.906175   GrowthHalo for ticker: NOW
2020-12-31   URI       NaN   18.575108   GrowthHalo for ticker: URI
2021-12-31   URI  0.560656   17.053835   GrowthHalo for ticker: URI
2022-12-31   URI  0.557248   11.713559   GrowthHalo for ticker: URI
2023-12-31   URI  0.189882   16.107012   GrowthHalo for ticker: URI

In [23]:
self = growth_scan_df.iloc[0]["GrowthHalo"]

In [45]:
self = GrowthHalo("NVDA", yearly_growth_sharpe=1.5, quarterly_growth_sharpe=0.8)
eps_growth_yearly = self.eps_yearly_growth.dropna()
eps_growth_quarterly = self.eps_quarterly_growth.dropna() * 4.0  # scale to annual number

In [48]:
eps_growth_yearly

2022-01-31    1.231884
2023-01-31   -0.548052
2024-01-31    5.856322
Name: DilutedEPS, dtype: object

In [49]:
eps_growth_quarterly

2023-07-31    8.195122
2023-10-31       1.936
2024-07-31    0.481605
Name: DilutedEPS, dtype: object

In [46]:
self.sharpe_mod_ratio(eps_growth_quarterly)

0.7785535066322627

In [47]:
self.sharpe_mod_ratio(eps_growth_yearly)

1.7321174063534965